// <auto-generated />
using System;
using FileCrud.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileCrud.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260722155910_filecrud")]
    partial class filecrud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileCrud.Models.Student", b =>
                {
                    b.Property<Guid>("StdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StdAge")
                        .HasColumnType("int");

                    b.Property<string>("StdEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdProfile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StdId");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
